// Citizenship-law facts — Asia (best-effort; verify before reliance).
export const LAWS = {
  AF: { d: true, y: 5, c: false },
  AM: { d: true, y: 5, c: false, n: 'Ethnic-Armenian descent/repatriation path.' },
  AZ: { d: true, y: 5, c: false },
  BH: { d: true, y: null, c: false, n: 'Naturalisation rarely granted.' },
  BD: { d: true, y: 5, c: true },
  BT: { d: true, y: null, c: false, n: 'Long residence (15+ yrs) and conditions.' },
  BN: { d: true, y: 15, c: false },
  KH: { d: true, y: 7, c: false },
  CN: { d: true, y: null, c: false, n: 'Descent limited; naturalisation very restricted; dual not allowed.' },
  GE: { d: true, y: 5, c: true },
  HK: { d: true, y: null, c: false, n: 'PRC nationality; naturalisation via PRC (restricted).' },
  IN: { d: true, y: 12, c: false, n: '12 yrs; no dual (OCI card instead).' },
  ID: { d: true, y: 5, c: false, n: 'Dual limited to children.' },
  IR: { d: true, y: 5, c: false, n: 'Descent via father; dual not recognised.' },
  IQ: { d: true, y: 10, c: false },
  IL: { d: true, y: 5, c: true, n: 'Law of Return (Jewish descent).' },
  JP: { d: true, y: 5, c: false, f: 0, n: 'Dual not allowed (choose by ~age 20-22).' },
  JO: { d: true, y: 15, c: false, n: 'Descent via Jordanian father.' },
  KZ: { d: true, y: 5, c: false },
  KW: { d: true, y: null, c: false, n: 'Naturalisation very restricted.' },
  KG: { d: true, y: 5, c: false },
  LA: { d: true, y: 10, c: false },
  LB: { d: true, y: 5, c: true, n: 'Descent via father.' },
  MO: { d: true, y: null, c: false, n: 'PRC nationality; restricted.' },
  MY: { d: true, y: 10, c: false, n: '10-12 yrs; dual not allowed.' },
  MV: { d: true, y: 12, c: false, n: 'Muslim requirement.' },
  MN: { d: true, y: 5, c: false },
  MM: { d: true, y: null, c: false, n: 'Restricted (1982 citizenship law).' },
  NP: { d: true, y: 15, c: false },
  KP: { d: true, y: null, c: false },
  OM: { d: true, y: 20, c: false, n: 'Restricted.' },
  PK: { d: true, y: 7, c: true, n: 'Dual with select countries.' },
  PS: { d: true, y: null, c: true, n: 'Descent via Palestinian father.' },
  PH: { d: true, y: 10, c: true, n: 'Dual via reacquisition (RA 9225).' },
  QA: { d: true, y: null, c: false, n: 'Naturalisation restricted.' },
  SA: { d: true, y: null, c: false, n: 'Naturalisation by decree (restricted).' },
  SG: { d: true, y: 2, c: false, n: '2 yrs as permanent resident (longer in practice); dual not allowed.' },
  KR: { d: true, y: 5, c: false, n: 'Dual restricted.' },
  LK: { d: true, y: 5, c: false, n: 'Dual restricted (application-based).' },
  SY: { d: true, y: 5, c: true },
  TW: { d: true, y: 5, c: false, n: 'Naturalised citizens generally must renounce prior nationality.' },
  TJ: { d: true, y: 5, c: false },
  TH: { d: true, y: 5, c: false, n: 'Dual not allowed for naturalised.' },
  TL: { d: true, y: 10, c: true },
  TR: { d: true, y: 5, c: true },
  TM: { d: true, y: 7, c: false },
  AE: { d: true, y: null, c: false, n: 'Naturalisation restricted (30 yrs or nomination).' },
  UZ: { d: true, y: 5, c: false },
  VN: { d: true, y: 5, c: false, n: 'Dual for overseas Vietnamese (exceptions).' },
  YE: { d: true, y: 5, c: false },
};
