// Citizenship-law facts Africa (best-effort; verify before reliance).
export const LAWS = {
  DZ: { d: true, y: 7, c: false },
  AO: { d: true, y: 10, c: false },
  BJ: { d: true, y: 5, c: true },
  BW: { d: true, y: 10, c: false },
  BF: { d: true, y: 10, c: true },
  BI: { d: true, y: 10, c: false },
  CM: { d: true, y: 5, c: false },
  CV: { d: true, y: 5, c: true },
  CF: { d: true, y: 5, c: true },
  TD: { d: true, y: 15, c: false },
  KM: { d: true, y: 10, c: false },
  CG: { d: true, y: 10, c: false },
  CD: { d: true, y: 10, c: false },
  CI: { d: true, y: 5, c: true },
  DJ: { d: true, y: 10, c: false },
  EG: { d: true, y: 10, c: true, cbi: true, n: 'Dual with approval; citizenship by investment.' },
  GQ: { d: true, y: 10, c: false },
  ER: { d: true, y: 5, c: false },
  SZ: { d: true, y: 5, c: false },
  ET: { d: true, y: 4, c: false },
  GA: { d: true, y: 10, c: false },
  GM: { d: true, y: 5, c: true },
  GH: { d: true, y: 5, c: true },
  GN: { d: true, y: 5, c: false },
  GW: { d: true, y: 5, c: true },
  KE: { d: true, y: 7, c: true },
  LS: { d: true, y: 5, c: false },
  LR: { d: true, y: 5, c: false, n: 'Naturalisation historically restricted by ancestry requirement.' },
  LY: { d: true, y: 10, c: false },
  MG: { d: true, y: 5, c: false },
  MW: { d: true, y: 5, c: false },
  ML: { d: true, y: 5, c: true },
  MR: { d: true, y: 5, c: false },
  MU: { d: true, y: 5, c: true },
  MA: { d: true, y: 5, c: false, n: 'Dual restricted for naturalised.' },
  MZ: { d: true, y: 5, c: false },
  NA: { d: true, y: 10, c: false },
  NE: { d: true, y: 10, c: false },
  NG: { d: true, y: 15, c: false, n: 'Dual only for Nigerian citizens by birth.' },
  RW: { d: true, y: 10, c: true },
  ST: { d: true, y: 5, c: true },
  SN: { d: true, y: 5, c: true },
  SC: { d: true, y: 5, c: true },
  SL: { d: true, y: 5, c: true },
  SO: { d: true, y: 7, c: false },
  ZA: { d: true, y: 5, c: true, n: 'Dual with retention.' },
  SS: { d: true, y: 10, c: false },
  SD: { d: true, y: 10, c: false },
  TZ: { d: true, y: 5, c: false },
  TG: { d: true, y: 5, c: true },
  TN: { d: true, y: 5, c: true },
  UG: { d: true, y: 10, c: true },
  ZM: { d: true, y: 5, c: false },
  ZW: { d: true, y: 5, c: false },
};
