// Tax & financial facts (best-effort, approximate; verify before reliance).
// pit = top personal income tax rate (%), cit = corporate tax rate (%), vat = standard VAT/GST rate (%),
// territorial = taxes only domestic-source income (vs worldwide), wealth = has a recurring wealth tax.
export const TAX = {
  // --- Americas ---
  AG: { pit: 0, cit: 25, vat: 15, territorial: true },
  AR: { pit: 35, cit: 35, vat: 21, territorial: false },
  BS: { pit: 0, cit: 0, vat: 10, territorial: true },
  BB: { pit: 28.5, cit: 9, vat: 17.5, territorial: false },
  BZ: { pit: 25, cit: 25, vat: 12.5, territorial: false },
  BO: { pit: 13, cit: 25, vat: 13, territorial: true },
  BR: { pit: 27.5, cit: 34, vat: 17, territorial: false },
  CA: { pit: 53.5, cit: 26.5, vat: 5, territorial: false },
  CL: { pit: 40, cit: 27, vat: 19, territorial: false },
  CO: { pit: 39, cit: 35, vat: 19, territorial: false },
  CR: { pit: 25, cit: 30, vat: 13, territorial: true },
  DM: { pit: 0, cit: 25, vat: 15, territorial: true },
  DO: { pit: 25, cit: 27, vat: 18, territorial: false },
  EC: { pit: 37, cit: 25, vat: 15, territorial: false },
  SV: { pit: 30, cit: 30, vat: 13, territorial: true },
  GD: { pit: 0, cit: 28, vat: 15, territorial: true },
  GT: { pit: 7, cit: 25, vat: 12, territorial: true },
  GY: { pit: 33.3, cit: 25, vat: 14, territorial: false },
  HT: { pit: 30, cit: 30, vat: 10, territorial: false },
  HN: { pit: 25, cit: 25, vat: 15, territorial: true },
  JM: { pit: 30, cit: 25, vat: 15, territorial: false },
  MX: { pit: 35, cit: 30, vat: 16, territorial: false },
  NI: { pit: 30, cit: 30, vat: 15, territorial: true },
  PA: { pit: 25, cit: 25, vat: 7, territorial: true },
  PY: { pit: 10, cit: 10, vat: 10, territorial: true },
  PE: { pit: 30, cit: 29.5, vat: 18, territorial: false },
  KN: { pit: 0, cit: 33, vat: 17, territorial: true },
  LC: { pit: 0, cit: 30, vat: 12.5, territorial: true },
  VC: { pit: 0, cit: 30, vat: 16, territorial: true },
  SR: { pit: 38, cit: 36, vat: 10, territorial: false },
  TT: { pit: 25, cit: 30, vat: 12.5, territorial: false },
  US: { pit: 37, cit: 21, vat: 0, territorial: false },
  UY: { pit: 36, cit: 25, vat: 22, territorial: true },
  VE: { pit: 34, cit: 34, vat: 16, territorial: false },

  // --- Europe ---
  AD: { pit: 10, cit: 10, vat: 4.5, territorial: false },
  AL: { pit: 23, cit: 15, vat: 20, territorial: false },
  AT: { pit: 55, cit: 23, vat: 20, territorial: false },
  BY: { pit: 13, cit: 20, vat: 20, territorial: false },
  BE: { pit: 50, cit: 25, vat: 21, territorial: false },
  BA: { pit: 10, cit: 10, vat: 17, territorial: false },
  BG: { pit: 10, cit: 10, vat: 20, territorial: false },
  HR: { pit: 36, cit: 18, vat: 25, territorial: false },
  CY: { pit: 35, cit: 12.5, vat: 19, territorial: false, nonDom: true },
  CZ: { pit: 23, cit: 21, vat: 21, territorial: false },
  DK: { pit: 55.9, cit: 22, vat: 25, territorial: false },
  EE: { pit: 20, cit: 20, vat: 22, territorial: false },
  FI: { pit: 51.25, cit: 20, vat: 25.5, territorial: false },
  FR: { pit: 45, cit: 25, vat: 20, territorial: false, wealth: true },
  DE: { pit: 45, cit: 30, vat: 19, territorial: false },
  GR: { pit: 44, cit: 22, vat: 24, territorial: false },
  HU: { pit: 15, cit: 9, vat: 27, territorial: false },
  IS: { pit: 46.25, cit: 21, vat: 24, territorial: false },
  IE: { pit: 40, cit: 12.5, vat: 23, territorial: false, nonDom: true },
  IT: { pit: 43, cit: 24, vat: 22, territorial: false, nonDom: true },
  XK: { pit: 10, cit: 10, vat: 18, territorial: false },
  LV: { pit: 31, cit: 20, vat: 21, territorial: false },
  LI: { pit: 22.4, cit: 12.5, vat: 8.1, territorial: false },
  LT: { pit: 20, cit: 15, vat: 21, territorial: false },
  LU: { pit: 42, cit: 24.94, vat: 16, territorial: false },
  MT: { pit: 35, cit: 35, vat: 18, territorial: true, nonDom: true },
  MD: { pit: 12, cit: 12, vat: 20, territorial: false },
  MC: { pit: 0, cit: 33.33, vat: 20, territorial: false },
  ME: { pit: 9, cit: 15, vat: 21, territorial: false },
  NL: { pit: 49.5, cit: 25.8, vat: 21, territorial: false, wealth: true },
  MK: { pit: 10, cit: 10, vat: 18, territorial: false },
  NO: { pit: 38.2, cit: 22, vat: 25, territorial: false, wealth: true },
  PL: { pit: 32, cit: 19, vat: 23, territorial: false },
  PT: { pit: 48, cit: 21, vat: 23, territorial: false },
  RO: { pit: 10, cit: 16, vat: 19, territorial: false },
  RU: { pit: 15, cit: 25, vat: 20, territorial: false },
  SM: { pit: 15, cit: 17, vat: 22, territorial: false },
  RS: { pit: 15, cit: 15, vat: 20, territorial: false },
  SK: { pit: 25, cit: 21, vat: 20, territorial: false },
  SI: { pit: 50, cit: 22, vat: 22, territorial: false },
  ES: { pit: 47, cit: 25, vat: 21, territorial: false, wealth: true },
  SE: { pit: 52, cit: 20.6, vat: 25, territorial: false },
  CH: { pit: 40, cit: 14.6, vat: 8.1, territorial: false, wealth: true },
  UA: { pit: 18, cit: 18, vat: 20, territorial: false },
  GB: { pit: 45, cit: 25, vat: 20, territorial: false, nonDom: true },
  VA: { pit: 0, cit: 0, vat: 0, territorial: true },

  // --- Asia ---
  AM: { pit: 20, cit: 18, vat: 20, territorial: false },
  AZ: { pit: 25, cit: 20, vat: 18, territorial: false },
  BH: { pit: 0, cit: 0, vat: 10, territorial: true },
  BD: { pit: 25, cit: 27.5, vat: 15, territorial: false },
  BN: { pit: 0, cit: 18.5, vat: 0, territorial: true },
  KH: { pit: 20, cit: 20, vat: 10, territorial: false },
  CN: { pit: 45, cit: 25, vat: 13, territorial: false },
  GE: { pit: 20, cit: 15, vat: 18, territorial: true },
  HK: { pit: 17, cit: 16.5, vat: 0, territorial: true },
  IN: { pit: 42.7, cit: 25, vat: 18, territorial: false },
  ID: { pit: 35, cit: 22, vat: 11, territorial: false },
  IR: { pit: 35, cit: 25, vat: 9, territorial: false },
  IQ: { pit: 15, cit: 15, vat: 0, territorial: false },
  IL: { pit: 50, cit: 23, vat: 17, territorial: false },
  JP: { pit: 55, cit: 29.74, vat: 10, territorial: false },
  JO: { pit: 30, cit: 20, vat: 16, territorial: false },
  KZ: { pit: 10, cit: 20, vat: 12, territorial: false },
  KW: { pit: 0, cit: 15, vat: 0, territorial: true },
  KG: { pit: 10, cit: 10, vat: 12, territorial: false },
  LA: { pit: 25, cit: 20, vat: 10, territorial: false },
  LB: { pit: 25, cit: 17, vat: 11, territorial: false },
  MO: { pit: 12, cit: 12, vat: 0, territorial: true },
  MY: { pit: 30, cit: 24, vat: 8, territorial: true },
  MV: { pit: 15, cit: 15, vat: 8, territorial: false },
  MN: { pit: 10, cit: 25, vat: 10, territorial: false },
  MM: { pit: 25, cit: 25, vat: 5, territorial: false },
  NP: { pit: 36, cit: 25, vat: 13, territorial: false },
  KP: { pit: 0, cit: 0, vat: 0, territorial: false },
  OM: { pit: 0, cit: 15, vat: 5, territorial: true },
  PK: { pit: 35, cit: 29, vat: 18, territorial: false },
  PS: { pit: 15, cit: 15, vat: 16, territorial: false },
  PH: { pit: 35, cit: 25, vat: 12, territorial: false },
  QA: { pit: 0, cit: 10, vat: 0, territorial: true },
  SA: { pit: 0, cit: 20, vat: 15, territorial: true },
  SG: { pit: 24, cit: 17, vat: 9, territorial: true },
  KR: { pit: 45, cit: 24, vat: 10, territorial: false },
  LK: { pit: 36, cit: 24, vat: 18, territorial: false },
  SY: { pit: 22, cit: 28, vat: 0, territorial: false },
  TW: { pit: 40, cit: 20, vat: 5, territorial: false },
  TJ: { pit: 13, cit: 25, vat: 14, territorial: false },
  TH: { pit: 35, cit: 20, vat: 7, territorial: true },
  TL: { pit: 10, cit: 10, vat: 0, territorial: false },
  TR: { pit: 40, cit: 25, vat: 20, territorial: false },
  TM: { pit: 10, cit: 20, vat: 15, territorial: false },
  AE: { pit: 0, cit: 9, vat: 5, territorial: true },
  UZ: { pit: 12, cit: 15, vat: 12, territorial: false },
  VN: { pit: 35, cit: 20, vat: 10, territorial: false },
  YE: { pit: 20, cit: 20, vat: 5, territorial: false },

  // --- Oceania ---
  AU: { pit: 45, cit: 30, vat: 10, territorial: false },
  FJ: { pit: 20, cit: 20, vat: 15, territorial: false },
  KI: { pit: 35, cit: 30, vat: 12.5, territorial: false },
  MH: { pit: 12, cit: 3, vat: 0, territorial: false },
  FM: { pit: 10, cit: 21, vat: 0, territorial: false },
  NR: { pit: 0, cit: 25, vat: 0, territorial: true },
  NZ: { pit: 39, cit: 28, vat: 15, territorial: false },
  PW: { pit: 9.3, cit: 0, vat: 10, territorial: false },
  PG: { pit: 42, cit: 30, vat: 10, territorial: false },
  WS: { pit: 27, cit: 27, vat: 15, territorial: false },
  SB: { pit: 40, cit: 30, vat: 15, territorial: false },
  TO: { pit: 20, cit: 25, vat: 15, territorial: false },
  TV: { pit: 0, cit: 0, vat: 0, territorial: false },
  VU: { pit: 0, cit: 0, vat: 15, territorial: true },

  // --- Africa ---
  DZ: { pit: 35, cit: 26, vat: 19, territorial: false },
  AO: { pit: 25, cit: 25, vat: 14, territorial: false },
  BJ: { pit: 45, cit: 30, vat: 18, territorial: false },
  BW: { pit: 25, cit: 22, vat: 14, territorial: false },
  BF: { pit: 27.5, cit: 27.5, vat: 18, territorial: false },
  BI: { pit: 35, cit: 30, vat: 18, territorial: false },
  CM: { pit: 38.5, cit: 33, vat: 19.25, territorial: false },
  CV: { pit: 27.5, cit: 22, vat: 15, territorial: false },
  CF: { pit: 50, cit: 30, vat: 19, territorial: false },
  TD: { pit: 30, cit: 35, vat: 18, territorial: false },
  KM: { pit: 30, cit: 50, vat: 0, territorial: false },
  CG: { pit: 30, cit: 28, vat: 18, territorial: false },
  CD: { pit: 40, cit: 30, vat: 16, territorial: false },
  CI: { pit: 60, cit: 25, vat: 18, territorial: false },
  DJ: { pit: 30, cit: 25, vat: 10, territorial: false },
  EG: { pit: 25, cit: 22.5, vat: 14, territorial: false },
  GQ: { pit: 35, cit: 35, vat: 15, territorial: false },
  ER: { pit: 30, cit: 30, vat: 0, territorial: false },
  SZ: { pit: 33, cit: 27.5, vat: 15, territorial: false },
  ET: { pit: 35, cit: 30, vat: 15, territorial: false },
  GA: { pit: 35, cit: 30, vat: 18, territorial: false },
  GM: { pit: 30, cit: 27, vat: 15, territorial: false },
  GH: { pit: 30, cit: 25, vat: 15, territorial: false },
  GN: { pit: 40, cit: 35, vat: 18, territorial: false },
  GW: { pit: 20, cit: 25, vat: 15, territorial: false },
  KE: { pit: 35, cit: 30, vat: 16, territorial: false },
  LS: { pit: 30, cit: 25, vat: 15, territorial: false },
  LR: { pit: 25, cit: 25, vat: 10, territorial: false },
  LY: { pit: 10, cit: 20, vat: 0, territorial: false },
  MG: { pit: 20, cit: 20, vat: 20, territorial: false },
  MW: { pit: 30, cit: 30, vat: 16.5, territorial: false },
  ML: { pit: 40, cit: 35, vat: 18, territorial: false },
  MR: { pit: 40, cit: 25, vat: 16, territorial: false },
  MU: { pit: 20, cit: 15, vat: 15, territorial: false },
  MA: { pit: 38, cit: 31, vat: 20, territorial: false },
  MZ: { pit: 32, cit: 32, vat: 16, territorial: false },
  NA: { pit: 37, cit: 32, vat: 15, territorial: false },
  NE: { pit: 35, cit: 30, vat: 19, territorial: false },
  NG: { pit: 24, cit: 30, vat: 7.5, territorial: false },
  RW: { pit: 30, cit: 30, vat: 18, territorial: false },
  ST: { pit: 25, cit: 25, vat: 15, territorial: false },
  SN: { pit: 40, cit: 30, vat: 18, territorial: false },
  SC: { pit: 15, cit: 25, vat: 15, territorial: true },
  SL: { pit: 30, cit: 30, vat: 15, territorial: false },
  SO: { pit: 0, cit: 0, vat: 0, territorial: false },
  ZA: { pit: 45, cit: 27, vat: 15, territorial: false },
  SS: { pit: 0, cit: 0, vat: 0, territorial: false },
  SD: { pit: 15, cit: 35, vat: 17, territorial: false },
  TZ: { pit: 30, cit: 30, vat: 18, territorial: false },
  TG: { pit: 35, cit: 27, vat: 18, territorial: false },
  TN: { pit: 35, cit: 25, vat: 19, territorial: false },
  UG: { pit: 40, cit: 30, vat: 18, territorial: false },
  ZM: { pit: 37.5, cit: 30, vat: 16, territorial: false },
  ZW: { pit: 36, cit: 24.72, vat: 15, territorial: false },
};
