// Citizenship-law facts — Europe (best-effort; verify before reliance).
// d = citizenshipByDescent (jus sanguinis), y = naturalisation years (null = restricted),
// c = dual citizenship allowed, f = official fee in EUR (null = varies), n = note.
export const LAWS = {
  AL: { d: true, y: 5, c: true },
  AD: { d: true, y: 20, c: false, n: 'Long residency (20 yrs); dual citizenship generally not allowed.' },
  AT: { d: true, y: 10, c: false, f: 1115, n: 'Dual citizenship restricted; fee ≈ €1,115.' },
  BY: { d: true, y: 5, c: false, n: 'Dual citizenship not recognised.' },
  BE: { d: true, y: 5, c: true, f: 150 },
  BA: { d: true, y: 8, c: true },
  BG: { d: true, y: 5, c: true, n: 'Descent extends to third generation.' },
  HR: { d: true, y: 8, c: true },
  CY: { d: true, y: 7, c: true },
  CZ: { d: true, y: 5, c: true },
  DK: { d: true, y: 9, c: true },
  EE: { d: true, y: 8, c: false, n: 'Dual citizenship restricted.' },
  FI: { d: true, y: 5, c: true },
  FR: { d: true, y: 5, c: true, f: 55 },
  DE: { d: true, y: 5, c: true, f: 255, n: '5 yrs (3 with exceptional integration); dual allowed since June 2024.' },
  GR: { d: true, y: 7, c: true },
  HU: { d: true, y: 8, c: true, n: 'Descent/simplified naturalisation for ethnic Hungarians.' },
  IS: { d: true, y: 7, c: true },
  IE: { d: true, y: 5, c: true, f: 175, n: 'Grandparent descent via Foreign Births Register; 5 yrs (3 if married to a citizen).' },
  IT: { d: true, y: 10, c: true, f: 250, n: 'Descent via ancestry (jure sanguinis, no generational limit); 10 yrs residence.' },
  XK: { d: true, y: 5, c: true },
  LV: { d: true, y: 5, c: true },
  LI: { d: true, y: 30, c: false, n: 'Very long residency; dual citizenship restricted.' },
  LT: { d: true, y: 10, c: false, n: 'Dual citizenship restricted.' },
  LU: { d: true, y: 5, c: true },
  MT: { d: true, y: 5, c: true, n: 'Also citizenship by investment.' },
  MD: { d: true, y: 10, c: true },
  MC: { d: true, y: 10, c: false, n: 'Dual citizenship not allowed.' },
  ME: { d: true, y: 10, c: true },
  NL: { d: true, y: 5, c: false, f: 1030, n: 'Dual citizenship restricted (exceptions apply); fee ≈ €1,030.' },
  MK: { d: true, y: 8, c: true },
  NO: { d: true, y: 7, c: true },
  PL: { d: true, y: 5, c: true, n: 'Descent to great-grandparents; 3 yrs for spouses/descent (Karta Polaka).' },
  PT: { d: true, y: 5, c: true, f: 250, n: 'Descent to grandparents (and Sephardic heritage); fee ≈ €250.' },
  RO: { d: true, y: 8, c: true },
  RU: { d: true, y: 5, c: true, n: 'Dual citizenship tolerated but not recognised.' },
  SM: { d: true, y: 30, c: false, n: 'Long residency (30 yrs, 15 for spouses); dual restricted.' },
  RS: { d: true, y: 3, c: true },
  SK: { d: true, y: 8, c: false, n: 'Descent to third generation; dual restricted.' },
  SI: { d: true, y: 10, c: false, n: 'Dual citizenship restricted.' },
  ES: { d: true, y: 10, c: false, f: 100, n: '10 yrs; dual only for Ibero-American and select countries.' },
  SE: { d: true, y: 5, c: true, f: 130, n: 'No citizenship test; fee SEK 1,500 (≈ €130).' },
  CH: { d: true, y: 10, c: true, n: 'Communal/cantonal approval required.' },
  UA: { d: true, y: 5, c: false, n: 'Dual citizenship not recognised.' },
  GB: { d: true, y: 5, c: true, f: 1760, n: 'Descent limited to one generation abroad (exceptions); fee ≈ £1,500.' },
  VA: { d: false, y: null, c: false, n: 'Citizenship tied to office/residence in Vatican City; no general naturalisation.' },
};
